package com.neoagent.flutter_app.widgets

import android.content.Context
import com.neoagent.flutter_app.R

/**
 * The mascot's moods as the widgets show them. Faces are generated by
 * `tool/render_widget_faces.dart`.
 */
internal enum class HomeWidgetMood(val face: Int, val label: Int, val changesSoon: Boolean = false) {
    IDLE(R.layout.neoagent_widget_face_idle, R.string.neoagent_widget_ready),
    LISTENING(R.layout.neoagent_widget_face_listening, R.string.neoagent_widget_listening),
    THINKING(R.layout.neoagent_widget_face_thinking, R.string.neoagent_widget_thinking, changesSoon = true),
    WORKING(R.layout.neoagent_widget_face_working, R.string.neoagent_widget_working, changesSoon = true),
    WAITING(R.layout.neoagent_widget_face_waiting, R.string.neoagent_widget_waiting, changesSoon = true),
    BLOCKED(R.layout.neoagent_widget_face_blocked, R.string.neoagent_widget_blocked),
    DONE(R.layout.neoagent_widget_face_done, R.string.neoagent_widget_done),
    ASLEEP(R.layout.neoagent_widget_face_asleep, R.string.neoagent_widget_offline);

    companion object {
        /** From `MascotMood.name` in the app. */
        fun of(name: String?): HomeWidgetMood =
            values().firstOrNull { it.name.equals(name, ignoreCase = true) } ?: IDLE
    }
}

/** What the widgets show: the app's last publish, or a background refresh. */
internal class HomeWidgetStatus(
    val mood: HomeWidgetMood,
    val detail: String,
    val live: Boolean,
    val callStartedAtMs: Long?,
    val updatedAtMs: Long,
) {
    companion object {
        private const val PREFS_NAME = "neoagent_home_widgets"
        private const val KEY_MOOD = "mood"
        private const val KEY_DETAIL = "detail"
        private const val KEY_LIVE = "live"
        private const val KEY_CALL_STARTED_AT = "call_started_at_ms"
        private const val KEY_UPDATED_AT = "updated_at_ms"

        /**
         * True once the running app published in this process. A widget
         * rendered in a fresh process shows a snapshot from an app that has
         * since died: it is not live and no call is open.
         */
        @Volatile
        private var publishedInThisProcess = false

        /** From the app, which is following the agent itself. */
        @Synchronized
        fun publish(
            context: Context,
            mood: HomeWidgetMood,
            detail: String,
            live: Boolean,
            callStartedAtMs: Long?,
        ) {
            store(context, mood, detail, live, callStartedAtMs)
            publishedInThisProcess = true
        }

        /**
         * From a background refresh. Skipped while the app is live: its own
         * state is newer than anything the server list says.
         */
        @Synchronized
        fun refresh(context: Context, mood: HomeWidgetMood, detail: String): Boolean {
            if (read(context)?.live == true) return false
            store(context, mood, detail, live = false, callStartedAtMs = null)
            return true
        }

        /** Null until the app has published once. */
        fun read(context: Context): HomeWidgetStatus? {
            val prefs = prefs(context)
            val updatedAt = prefs.getLong(KEY_UPDATED_AT, 0L)
            if (updatedAt == 0L) return null
            val appRunning = publishedInThisProcess
            return HomeWidgetStatus(
                mood = HomeWidgetMood.of(prefs.getString(KEY_MOOD, null)),
                detail = prefs.getString(KEY_DETAIL, null).orEmpty(),
                live = appRunning && prefs.getBoolean(KEY_LIVE, false),
                callStartedAtMs = prefs.getLong(KEY_CALL_STARTED_AT, 0L)
                    .takeIf { appRunning && it > 0L },
                updatedAtMs = updatedAt,
            )
        }

        private fun store(
            context: Context,
            mood: HomeWidgetMood,
            detail: String,
            live: Boolean,
            callStartedAtMs: Long?,
        ) {
            prefs(context)
                .edit()
                .putString(KEY_MOOD, mood.name)
                .putString(KEY_DETAIL, detail)
                .putBoolean(KEY_LIVE, live)
                .putLong(KEY_CALL_STARTED_AT, callStartedAtMs ?: 0L)
                .putLong(KEY_UPDATED_AT, System.currentTimeMillis())
                .apply()
        }

        private fun prefs(context: Context) =
            context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
    }
}
