#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { SETUP_CONTRACT } = require('../lib/setup/contract');
const {
  canonicalRuntimeSigningPublicKey,
} = require('../lib/setup/runtime_manifest');

const outputPath = path.join(
  __dirname,
  '..',
  'flutter_app',
  'lib',
  'src',
  'setup_contract.g.dart',
);

function dartString(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderStringList(name, values) {
  if (values.length <= 2) {
    return `const List<String> ${name} = <String>[${values.map(dartString).join(', ')}];`;
  }
  return [
    `const List<String> ${name} = <String>[`,
    ...values.map((value) => `  ${dartString(value)},`),
    '];',
  ].join('\n');
}

function renderContract() {
  const profiles = Object.values(SETUP_CONTRACT.profiles);
  const targets = Object.entries(SETUP_CONTRACT.runtimeTargets);
  return [
    '// Generated by scripts/generate_setup_contract.js. Do not edit.',
    '',
    `const int setupContractSchemaVersion = ${SETUP_CONTRACT.schemaVersion};`,
    `const int neoAgentDefaultPort = ${SETUP_CONTRACT.defaultPort};`,
    `const String neoAgentDefaultPortText = '${SETUP_CONTRACT.defaultPort}';`,
    `const String embeddedRuntimeSigningPublicKey = ${dartString(canonicalRuntimeSigningPublicKey())};`,
    '',
    renderStringList(
      'setupProfileIds',
      profiles.map((profile) => profile.id),
    ),
    '',
    renderStringList(
      'setupCompletionSections',
      SETUP_CONTRACT.completionSections,
    ),
    '',
    renderStringList(
      'setupWizardSectionIds',
      SETUP_CONTRACT.wizardSections.map((section) => section.id),
    ),
    '',
    renderStringList('setupEventStages', SETUP_CONTRACT.eventStages),
    '',
    renderStringList(
      'setupResumeValueKeys',
      SETUP_CONTRACT.resumeValueKeys,
    ),
    '',
    'const Map<String, List<String>> setupRuntimeTargets = <String, List<String>>{',
    ...targets.map(([platform, architectures]) => (
      `  ${dartString(platform)}: <String>[${architectures.map(dartString).join(', ')}],`
    )),
    '};',
    '',
  ].join('\n');
}

function main(args = process.argv.slice(2)) {
  const generated = renderContract();
  if (args.includes('--check')) {
    const current = fs.existsSync(outputPath)
      ? fs.readFileSync(outputPath, 'utf8')
      : '';
    if (current !== generated) {
      const error = new Error(
        'Generated Flutter setup contract is stale. Run node scripts/generate_setup_contract.js.',
      );
      error.code = 'SETUP_CONTRACT_STALE';
      throw error;
    }
  } else {
    fs.writeFileSync(outputPath, generated);
  }
}

if (require.main === module) main();

module.exports = {
  main,
  outputPath,
  renderContract,
};
