// Generates the animated mascot faces of the Android home-screen widgets from
// the app's own frames and painter. Widgets cannot run Flutter, so each mood
// becomes native resources the launcher plays by itself:
//
//   res/drawable-nodpi/neoagent_face_<mood>_<n>.png  one PNG per distinct frame
//   res/drawable/neoagent_face_<mood>.xml            the loop, as an animation-list
//   res/layout/neoagent_widget_face_<mood>.xml       a ProgressBar that plays it
//
// Rerun after changing the mascot's frames or painter:
//
//   flutter test tool/render_widget_faces.dart
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:neoagent_flutter/src/mascot/mascot_frames.dart';
import 'package:neoagent_flutter/src/mascot/mascot_mood.dart';
import 'package:neoagent_flutter/src/mascot/neo_mascot.dart';

const String _res = 'android/app/src/main/res';

/// Widget faces show at up to 64dp; 160px stays sharp at xxhdpi without
/// making the launcher hold large bitmaps.
const int _size = 160;

const String _header =
    '<!-- Generated by tool/render_widget_faces.dart. Do not edit. -->';

typedef _Step = ({MascotFrame frame, int holdMs});

List<_Step> _steps(MascotClip clip) => <_Step>[
  for (final frame in clip.frames)
    (frame: frame, holdMs: frame.hold.inMilliseconds),
];

_Step _rest(int holdMs) => (frame: MascotClips.idleFace, holdMs: holdMs);

/// The loop a widget plays for [mood]. In the app, idle moves at random and
/// done plays once; a widget loop cannot script either, so idle gets a fixed
/// round of blinks and glances and done holds its smile before replaying.
List<_Step> _loop(MascotMood mood) => switch (mood) {
  MascotMood.idle => <_Step>[
    _rest(3200),
    ..._steps(MascotClips.blink),
    _rest(2600),
    ..._steps(MascotClips.glanceRight),
    _rest(2800),
    ..._steps(MascotClips.blink),
    _rest(2200),
    ..._steps(MascotClips.glanceLeft),
  ],
  // Every other comet step at twice the hold: the same speed with half the
  // bitmaps for the launcher to keep.
  MascotMood.working => <_Step>[
    for (final (index, step) in _steps(MascotClips.working).indexed)
      if (index.isEven) (frame: step.frame, holdMs: step.holdMs * 2),
  ],
  MascotMood.done => <_Step>[
    ..._steps(MascotClips.done).take(MascotClips.done.frames.length - 1),
    (frame: MascotClips.done.frames.last, holdMs: 3000),
  ],
  _ => _steps(MascotClips.forMood(mood)),
};

/// Cross-fade between frames. A fade longer than the shortest hold would
/// blur the stepped LED motion, so fast loops step without one.
int _fadeMs(MascotMood mood, List<_Step> loop) {
  final fade = mood == MascotMood.idle
      ? MascotClips.blink.fade.inMilliseconds
      : MascotClips.forMood(mood).fade.inMilliseconds;
  final shortest = loop
      .map((step) => step.holdMs)
      .reduce((a, b) => a < b ? a : b);
  return fade < shortest ? fade : 0;
}

String _look(MascotFrame frame) =>
    '${frame.dots.join(',')}|${frame.alert}|${frame.shift}|${frame.scale}|${frame.rim}';

void main() {
  test('render the widget faces', () async {
    final frames = Directory('$_res/drawable-nodpi')..createSync();
    for (final file in frames.listSync()) {
      if (file.uri.pathSegments.last.startsWith('neoagent_face_')) {
        file.deleteSync();
      }
    }
    for (final mood in MascotMood.values) {
      final name = 'neoagent_face_${mood.name}';
      final loop = _loop(mood);
      // Frames that look the same share one PNG.
      final drawables = <String, String>{};
      for (final step in loop) {
        final look = _look(step.frame);
        if (drawables.containsKey(look)) continue;
        final drawable = '${name}_${drawables.length}';
        drawables[look] = drawable;
        File(
          '$_res/drawable-nodpi/$drawable.png',
        ).writeAsBytesSync(await renderMascotFramePng(step.frame, size: _size));
      }

      final fade = _fadeMs(mood, loop);
      final items = loop
          .map(
            (step) =>
                '    <item android:drawable="@drawable/${drawables[_look(step.frame)]}" '
                'android:duration="${step.holdMs}" />',
          )
          .join('\n');
      File('$_res/drawable/$name.xml').writeAsStringSync('''
<?xml version="1.0" encoding="utf-8"?>
$_header
<animation-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:enterFadeDuration="$fade"
    android:exitFadeDuration="$fade"
    android:oneshot="false">
$items
</animation-list>
''');

      // An indeterminate ProgressBar starts its drawable by itself, which an
      // ImageView in a widget never does. Multiplying by white keeps any
      // theme tint off the face.
      File(
        '$_res/layout/neoagent_widget_face_${mood.name}.xml',
      ).writeAsStringSync('''
<?xml version="1.0" encoding="utf-8"?>
$_header
<ProgressBar xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:importantForAccessibility="no"
    android:indeterminate="true"
    android:indeterminateDrawable="@drawable/$name"
    android:indeterminateOnly="true"
    android:indeterminateTint="@android:color/white"
    android:indeterminateTintMode="multiply"
    android:maxWidth="512dp"
    android:maxHeight="512dp"
    android:minWidth="0dp"
    android:minHeight="0dp" />
''');
    }
  });
}
