// Generated by scripts/generate_setup_contract.js. Do not edit.

const int setupContractSchemaVersion = 1;
const int neoAgentDefaultPort = 3333;
const String neoAgentDefaultPortText = '3333';

const List<String> setupProfileIds = <String>['quick', 'full'];

const List<String> setupCompletionSections = <String>[
  'core',
  'network',
  'providers',
  'integrations',
  'voice',
  'optional-capabilities',
];

const List<String> setupWizardSectionIds = <String>[
  'core',
  'providers',
  'integrations',
  'voice',
  'review',
];

const List<String> setupEventStages = <String>[
  'prepare',
  'configuration',
  'dependencies',
  'download',
  'verify',
  'install',
  'service',
  'connect',
  'complete',
  'status',
  'doctor',
  'setup',
];

const List<String> setupResumeValueKeys = <String>[
  'PORT',
  'PUBLIC_URL',
  'SECURE_COOKIES',
  'TRUST_PROXY',
  'NEOAGENT_DEPLOYMENT_MODE',
  'NEOAGENT_RELEASE_CHANNEL',
  'ALLOWED_ORIGINS',
  'ANTHROPIC_BASE_URL',
  'OPENAI_BASE_URL',
  'XAI_BASE_URL',
  'OLLAMA_URL',
  'GOOGLE_OAUTH_REDIRECT_URI',
  'NOTION_OAUTH_REDIRECT_URI',
  'MICROSOFT_OAUTH_REDIRECT_URI',
  'MICROSOFT_OAUTH_TENANT_ID',
  'SLACK_OAUTH_REDIRECT_URI',
  'FIGMA_OAUTH_REDIRECT_URI',
  'GITHUB_OAUTH_REDIRECT_URI',
  'DEEPGRAM_BASE_URL',
  'DEEPGRAM_MODEL',
  'DEEPGRAM_LANGUAGE',
];

const Map<String, List<String>> setupRuntimeTargets = <String, List<String>>{
  'macos': <String>['x64', 'arm64'],
  'windows': <String>['x64', 'arm64'],
  'linux': <String>['x64'],
};
